package de.greenrobot.daotest;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.platform.java.util.JDBCUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table RELATION_ENTITY.
*/
public class RelationEntityDao extends AbstractDao<RelationEntity, Long> {

    public static final String TABLENAME = "RELATION_ENTITY";

    /**
     * Properties of entity RelationEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ParentId = new Property(1, Long.class, "parentId", false, "PARENT_ID");
        public final static Property TestId = new Property(2, Long.class, "testId", false, "TEST_ID");
        public final static Property TestIdNotNull = new Property(3, long.class, "testIdNotNull", false, "TEST_ID_NOT_NULL");
        public final static Property SimpleString = new Property(4, String.class, "simpleString", false, "SIMPLE_STRING");
        public final static Property TestWithoutProperty = new Property(5, Long.class, "testWithoutProperty", false, "WITHOUT_PROPERTY_TEST_ID");
    };

    private DaoSession daoSession;


    public RelationEntityDao(DaoConfig config) {
        super(config);
    }
    
    public RelationEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. 
     * @throws SQLException */
    public static void createTable(Connection connection, boolean ifNotExists) throws SQLException {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        JDBCUtils.execute(connection, "CREATE TABLE " + constraint + "'RELATION_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'PARENT_ID' INTEGER," + // 1: parentId
                "'TEST_ID' INTEGER," + // 2: testId
                "'TEST_ID_NOT_NULL' INTEGER NOT NULL ," + // 3: testIdNotNull
                "'SIMPLE_STRING' TEXT," + // 4: simpleString
                "'WITHOUT_PROPERTY_TEST_ID' INTEGER);"); // 5: testWithoutProperty
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'RELATION_ENTITY'";
        db.execSQL(sql);
    }

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    protected void bindValues(PreparedStatement stmt, RelationEntity entity) throws SQLException {
//        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.setLong(1, id);
        }
 
        Long parentId = entity.getParentId();
        if (parentId != null) {
            stmt.setLong(2, parentId);
        }
 
        Long testId = entity.getTestId();
        if (testId != null) {
            stmt.setLong(3, testId);
        }
        stmt.setLong(4, entity.getTestIdNotNull());
 
        String simpleString = entity.getSimpleString();
        if (simpleString != null) {
            stmt.setString(5, simpleString);
        }
    }

    @Override
    protected void attachEntity(RelationEntity entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public Long readKey(ResultSet resultSet, int offset) throws SQLException {
        return JDBCUtils.isNull(resultSet, offset + 0) ? null : resultSet.getLong(offset + 0);
    }    

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public RelationEntity readEntity(ResultSet resultSet, int offset) throws SQLException {
        RelationEntity entity = new RelationEntity( //
            JDBCUtils.isNull(resultSet, offset + 0) ? null : resultSet.getLong(offset + 0), // id
            JDBCUtils.isNull(resultSet, offset + 1) ? null : resultSet.getLong(offset + 1), // parentId
            JDBCUtils.isNull(resultSet, offset + 2) ? null : resultSet.getLong(offset + 2), // testId
            resultSet.getLong(offset + 3), // testIdNotNull
            JDBCUtils.isNull(resultSet, offset + 4) ? null : resultSet.getString(offset + 4) // simpleString
        );
        return entity;
    }
     
    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public void readEntity(ResultSet resultSet, RelationEntity entity, int offset) throws SQLException {
        entity.setId(JDBCUtils.isNull( resultSet, offset + 0) ? null : resultSet.getLong(offset + 0));
        entity.setParentId(JDBCUtils.isNull( resultSet, offset + 1) ? null : resultSet.getLong(offset + 1));
        entity.setTestId(JDBCUtils.isNull( resultSet, offset + 2) ? null : resultSet.getLong(offset + 2));
        entity.setTestIdNotNull(resultSet.getLong(offset + 3));
        entity.setSimpleString(JDBCUtils.isNull( resultSet, offset + 4) ? null : resultSet.getString(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(RelationEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(RelationEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getRelationEntityDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTestEntityDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getTestEntityDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T3", daoSession.getTestEntityDao().getAllColumns());
            builder.append(" FROM RELATION_ENTITY T");
            builder.append(" LEFT JOIN RELATION_ENTITY T0 ON T.'PARENT_ID'=T0.'_id'");
            builder.append(" LEFT JOIN TEST_ENTITY T1 ON T.'TEST_ID'=T1.'_id'");
            builder.append(" LEFT JOIN TEST_ENTITY T2 ON T.'TEST_ID_NOT_NULL'=T2.'_id'");
            builder.append(" LEFT JOIN TEST_ENTITY T3 ON T.'WITHOUT_PROPERTY_TEST_ID'=T3.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected RelationEntity loadCurrentDeep(ResultSet resultSet, boolean lock) throws SQLException {
        RelationEntity entity = loadCurrent(resultSet, 0, lock);
        int offset = getAllColumns().length;

        RelationEntity parent = loadCurrentOther(daoSession.getRelationEntityDao(), resultSet, offset);
        entity.setParent(parent);
        offset += daoSession.getRelationEntityDao().getAllColumns().length;

        TestEntity testEntity = loadCurrentOther(daoSession.getTestEntityDao(), resultSet, offset);
        entity.setTestEntity(testEntity);
        offset += daoSession.getTestEntityDao().getAllColumns().length;

        TestEntity testNotNull = loadCurrentOther(daoSession.getTestEntityDao(), resultSet, offset);
         if(testNotNull != null) {
            entity.setTestNotNull(testNotNull);
        }
        offset += daoSession.getTestEntityDao().getAllColumns().length;

        TestEntity testWithoutProperty = loadCurrentOther(daoSession.getTestEntityDao(), resultSet, offset);
        entity.setTestWithoutProperty(testWithoutProperty);

        return entity;    
    }

    public RelationEntity loadDeep(Long key) throws SQLException {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        ResultSet resultSet = JDBCUtils.query( connection, sql, (Object[]) keyArray );
        
        try {
            boolean available = resultSet.first();
            if (!available) {
                return null;
            } else if (!resultSet.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + resultSet.getFetchSize());
            }
            return loadCurrentDeep(resultSet, true);
        } finally {
            resultSet.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. 
     * @throws SQLException */
    public List<RelationEntity> loadAllDeepFromCursor(ResultSet resultSet) throws SQLException {
        int count = resultSet.getFetchSize();
        List<RelationEntity> list = new ArrayList<RelationEntity>(count);
        
        if (resultSet.first()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(resultSet, false));
                } while (resultSet.next());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<RelationEntity> loadDeepAllAndCloseCursor(ResultSet resultSet) throws SQLException {
        try {
            return loadAllDeepFromCursor(resultSet);
        } finally {
            resultSet.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. 
     * @throws SQLException */
    public List<RelationEntity> queryDeep(String where, String... selectionArg) throws SQLException {
    	//@formatter:off
    	ResultSet resultSet = JDBCUtils.query( 
    			connection, 
    			getSelectDeep() + where, 
    			(Object[]) selectionArg
    	);
    	//@formatter:on
        return loadDeepAllAndCloseCursor(resultSet);
    }
 
}
