package de.greenrobot.daotest;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.platform.java.util.JDBCUtils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table SIMPLE_ENTITY.
*/
public class SimpleEntityDao extends AbstractDao<SimpleEntity, Long> {

    public static final String TABLENAME = "SIMPLE_ENTITY";

    /**
     * Properties of entity SimpleEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property SimpleBoolean = new Property(1, Boolean.class, "simpleBoolean", false, "SIMPLE_BOOLEAN");
        public final static Property SimpleByte = new Property(2, Byte.class, "simpleByte", false, "SIMPLE_BYTE");
        public final static Property SimpleShort = new Property(3, Short.class, "simpleShort", false, "SIMPLE_SHORT");
        public final static Property SimpleInt = new Property(4, Integer.class, "simpleInt", false, "SIMPLE_INT");
        public final static Property SimpleLong = new Property(5, Long.class, "simpleLong", false, "SIMPLE_LONG");
        public final static Property SimpleFloat = new Property(6, Float.class, "simpleFloat", false, "SIMPLE_FLOAT");
        public final static Property SimpleDouble = new Property(7, Double.class, "simpleDouble", false, "SIMPLE_DOUBLE");
        public final static Property SimpleString = new Property(8, String.class, "simpleString", false, "SIMPLE_STRING");
        public final static Property SimpleByteArray = new Property(9, byte[].class, "simpleByteArray", false, "SIMPLE_BYTE_ARRAY");
    };


    public SimpleEntityDao(DaoConfig config) {
        super(config);
    }
    
    public SimpleEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. 
     * @throws ` */
    public static void createTable(Connection connection, boolean ifNotExists) throws SQLException {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        String sql = "CREATE TABLE " + constraint + "'SIMPLE_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'SIMPLE_BOOLEAN' INTEGER," + // 1: simpleBoolean
                "'SIMPLE_BYTE' INTEGER," + // 2: simpleByte
                "'SIMPLE_SHORT' INTEGER," + // 3: simpleShort
                "'SIMPLE_INT' INTEGER," + // 4: simpleInt
                "'SIMPLE_LONG' INTEGER," + // 5: simpleLong
                "'SIMPLE_FLOAT' REAL," + // 6: simpleFloat
                "'SIMPLE_DOUBLE' REAL," + // 7: simpleDouble
                "'SIMPLE_STRING' TEXT," + // 8: simpleString
                "'SIMPLE_BYTE_ARRAY' BLOB);"; // 9: simpleByteArray
        JDBCUtils.execute( connection, sql );
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'SIMPLE_ENTITY'";
        db.execSQL(sql);
    }

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    protected void bindValues(PreparedStatement stmt, SimpleEntity entity) throws SQLException {
//        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.setLong(1, id);
        }
 
        Boolean simpleBoolean = entity.getSimpleBoolean();
        if (simpleBoolean != null) {
            stmt.setLong(2, simpleBoolean ? 1l: 0l);
        }
 
        Byte simpleByte = entity.getSimpleByte();
        if (simpleByte != null) {
            stmt.setLong(3, simpleByte);
        }
 
        Short simpleShort = entity.getSimpleShort();
        if (simpleShort != null) {
            stmt.setLong(4, simpleShort);
        }
 
        Integer simpleInt = entity.getSimpleInt();
        if (simpleInt != null) {
            stmt.setLong(5, simpleInt);
        }
 
        Long simpleLong = entity.getSimpleLong();
        if (simpleLong != null) {
            stmt.setLong(6, simpleLong);
        }
 
        Float simpleFloat = entity.getSimpleFloat();
        if (simpleFloat != null) {
            stmt.setDouble(7, simpleFloat);
        }
 
        Double simpleDouble = entity.getSimpleDouble();
        if (simpleDouble != null) {
            stmt.setDouble(8, simpleDouble);
        }
 
        String simpleString = entity.getSimpleString();
        if (simpleString != null) {
            stmt.setString(9, simpleString);
        }
 
        byte[] simpleByteArray = entity.getSimpleByteArray();
        if (simpleByteArray != null) {
            stmt.setBytes(10, simpleByteArray);
        }
    }

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public Long readKey(ResultSet resultSet, int offset) throws SQLException {
        return JDBCUtils.isNull( resultSet, offset + 0 ) ? null : resultSet.getLong(offset + 0);
    }    

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public SimpleEntity readEntity(ResultSet resultSet, int offset) throws SQLException {
        SimpleEntity entity = new SimpleEntity( //
            JDBCUtils.isNull( resultSet, offset + 0 ) ? null : resultSet.getLong(offset + 0), // id
            JDBCUtils.isNull( resultSet, offset + 1 ) ? null : resultSet.getShort(offset + 1) != 0, // simpleBoolean
            JDBCUtils.isNull( resultSet, offset + 2 ) ? null : (byte) resultSet.getShort(offset + 2), // simpleByte
            JDBCUtils.isNull( resultSet, offset + 3 ) ? null : resultSet.getShort(offset + 3), // simpleShort
            JDBCUtils.isNull( resultSet, offset + 4 ) ? null : resultSet.getInt(offset + 4), // simpleInt
            JDBCUtils.isNull( resultSet, offset + 5 ) ? null : resultSet.getLong(offset + 5), // simpleLong
            JDBCUtils.isNull( resultSet, offset + 6 ) ? null : resultSet.getFloat(offset + 6), // simpleFloat
            JDBCUtils.isNull( resultSet, offset + 7 ) ? null : resultSet.getDouble(offset + 7), // simpleDouble
            JDBCUtils.isNull( resultSet, offset + 8 ) ? null : resultSet.getString(offset + 8), // simpleString
            JDBCUtils.isNull( resultSet, offset + 9 ) ? null : resultSet.getBytes(offset + 9) // simpleByteArray
        );
        return entity;
    }
     
    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public void readEntity(ResultSet resultSet, SimpleEntity entity, int offset) throws SQLException {
        entity.setId(JDBCUtils.isNull( resultSet, offset + 0 ) ? null : resultSet.getLong(offset + 0));
        entity.setSimpleBoolean(JDBCUtils.isNull( resultSet, offset + 1) ? null : resultSet.getShort(offset + 1) != 0);
        entity.setSimpleByte(JDBCUtils.isNull( resultSet, offset + 2) ? null : (byte) resultSet.getShort(offset + 2));
        entity.setSimpleShort(JDBCUtils.isNull( resultSet, offset + 3) ? null : resultSet.getShort(offset + 3));
        entity.setSimpleInt(JDBCUtils.isNull( resultSet, offset + 4) ? null : resultSet.getInt(offset + 4));
        entity.setSimpleLong(JDBCUtils.isNull( resultSet, offset + 5) ? null : resultSet.getLong(offset + 5));
        entity.setSimpleFloat(JDBCUtils.isNull( resultSet, offset + 6) ? null : resultSet.getFloat(offset + 6));
        entity.setSimpleDouble(JDBCUtils.isNull( resultSet, offset + 7) ? null : resultSet.getDouble(offset + 7));
        entity.setSimpleString(JDBCUtils.isNull( resultSet, offset + 8) ? null : resultSet.getString(offset + 8));
        entity.setSimpleByteArray(JDBCUtils.isNull( resultSet, offset + 9) ? null : resultSet.getBytes(offset + 9));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(SimpleEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(SimpleEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
