package de.greenrobot.daotest;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;

import de.greenrobot.dao.internal.JDBCUtils;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daotest.StringKeyValueEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STRING_KEY_VALUE_ENTITY.
*/
public class StringKeyValueEntityDao extends AbstractDao<StringKeyValueEntity, String> {

    public static final String TABLENAME = "STRING_KEY_VALUE_ENTITY";

    /**
     * Properties of entity StringKeyValueEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Key = new Property(0, String.class, "key", true, "KEY");
        public final static Property Value = new Property(1, String.class, "value", false, "VALUE");
    };


    public StringKeyValueEntityDao(DaoConfig config) {
        super(config);
    }
    
    public StringKeyValueEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Connection connection, boolean ifNotExists) throws SQLException {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        JDBCUtils.execute( connection, "CREATE TABLE " + constraint + "'STRING_KEY_VALUE_ENTITY' (" + //
                "'KEY' TEXT PRIMARY KEY NOT NULL ," + // 0: key
                "'VALUE' TEXT);"); // 1: value
    }

    /** Drops the underlying database table. */
    public static void dropTable(Connection connection, boolean ifExists) throws SQLException {
        JDBCUtils.execute( connection, "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STRING_KEY_VALUE_ENTITY'");
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(PreparedStatement statement, StringKeyValueEntity entity) throws SQLException {
 
        String key = entity.getKey();
        if (key != null) {
            statement.setString(1, key);
        }
 
        String value = entity.getValue();
        if (value != null) {
            statement.setString(2, value);
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(ResultSet resultSet, int offset) throws SQLException {
        return JDBCUtils.isNull(resultSet, offset + 1) ? null : resultSet.getString(offset + 1);
    }    

    /** @inheritdoc */
    @Override
    public StringKeyValueEntity readEntity(ResultSet resultSet, int offset) throws SQLException {
		int index = 1;
        StringKeyValueEntity entity = new StringKeyValueEntity(
            JDBCUtils.isNull(resultSet, offset + index) ? null : resultSet.getString(offset + index++), // key
            JDBCUtils.isNull(resultSet, offset + index) ? null : resultSet.getString(offset + index++) // value
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(ResultSet resultSet, StringKeyValueEntity entity, int offset) throws SQLException {
		int index = 1;
        entity.setKey(JDBCUtils.isNull(resultSet, offset + index) ? null : resultSet.getString(offset + index++));
        entity.setValue(JDBCUtils.isNull(resultSet, offset + index) ? null : resultSet.getString(offset + index++));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(StringKeyValueEntity entity, long rowId) {
        return entity.getKey();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(StringKeyValueEntity entity) {
        if(entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
