package de.greenrobot.daotest;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.JDBCUtils;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table STRING_KEY_VALUE_ENTITY.
*/
public class StringKeyValueEntityDao extends AbstractDao<StringKeyValueEntity, String> {

    public static final String TABLENAME = "STRING_KEY_VALUE_ENTITY";

    /**
     * Properties of entity StringKeyValueEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Key = new Property(0, String.class, "key", true, "KEY");
        public final static Property Value = new Property(1, String.class, "value", false, "VALUE");
    };


    public StringKeyValueEntityDao(DaoConfig config) {
        super(config);
    }
    
    public StringKeyValueEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. 
     * @throws SQLException */
    public static void createTable(Connection connection, boolean ifNotExists) throws SQLException {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        JDBCUtils.execute(connection, "CREATE TABLE " + constraint + "'STRING_KEY_VALUE_ENTITY' (" + //
                "'KEY' TEXT PRIMARY KEY NOT NULL ," + // 0: key
                "'VALUE' TEXT);"); // 1: value
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'STRING_KEY_VALUE_ENTITY'";
        db.execSQL(sql);
    }

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    protected void bindValues(PreparedStatement stmt, StringKeyValueEntity entity) throws SQLException {
//        stmt.clearBindings();
 
        String key = entity.getKey();
        if (key != null) {
            stmt.setString(1, key);
        }
 
        String value = entity.getValue();
        if (value != null) {
            stmt.setString(2, value);
        }
    }

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public String readKey(ResultSet resultSet, int offset) throws SQLException {
        return JDBCUtils.isNull(resultSet, offset + 0) ? null : resultSet.getString(offset + 0);
    }    

    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public StringKeyValueEntity readEntity(ResultSet resultSet, int offset) throws SQLException {
        StringKeyValueEntity entity = new StringKeyValueEntity( //
            JDBCUtils.isNull(resultSet, offset + 0) ? null : resultSet.getString(offset + 0), // key
            JDBCUtils.isNull(resultSet, offset + 1) ? null : resultSet.getString(offset + 1) // value
        );
        return entity;
    }
     
    /** @throws SQLException 
     * @inheritdoc */
    @Override
    public void readEntity(ResultSet resultSet, StringKeyValueEntity entity, int offset) throws SQLException {
        entity.setKey(JDBCUtils.isNull(resultSet, offset + 0) ? null : resultSet.getString(offset + 0));
        entity.setValue(JDBCUtils.isNull(resultSet, offset + 1) ? null : resultSet.getString(offset + 1));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(StringKeyValueEntity entity, long rowId) {
        return entity.getKey();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(StringKeyValueEntity entity) {
        if(entity != null) {
            return entity.getKey();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
