package de.greenrobot.daotest2.to1_specialdao;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;

import de.greenrobot.platform.java.util.JDBCUtils;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import de.greenrobot.daotest2.dao.DaoSession;

import de.greenrobot.daotest2.to1_specialentity.ToOneTarget2;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table TO_ONE_TARGET2.
*/
public class ToOneTarget2Dao extends AbstractDao<ToOneTarget2, Long> {

    public static final String TABLENAME = "TO_ONE_TARGET2";

    /**
     * Properties of entity ToOneTarget2.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
    };


    public ToOneTarget2Dao(DaoConfig config) {
        super(config);
    }
    
    public ToOneTarget2Dao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Connection connection, boolean ifNotExists) throws SQLException {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        JDBCUtils.execute( connection, "CREATE TABLE " + constraint + "'TO_ONE_TARGET2' (" + //
                "'_id' INTEGER PRIMARY KEY );"); // 0: id
    }

    /** Drops the underlying database table. */
    public static void dropTable(Connection connection, boolean ifExists) throws SQLException {
        JDBCUtils.execute( connection, "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'TO_ONE_TARGET2'");
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(PreparedStatement statement, ToOneTarget2 entity) throws SQLException {
 
        Long id = entity.getId();
        if (id != null) {
            statement.setLong(1, id);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(ResultSet resultSet, int offset) throws SQLException {
    	int index = 1;
        return JDBCUtils.isNull(resultSet, offset + index) ? null : resultSet.getLong(offset + index++);
    }    

    /** @inheritdoc */
    @Override
    public ToOneTarget2 readEntity(ResultSet resultSet, int offset) throws SQLException {
		int index = 1;
        ToOneTarget2 entity = new ToOneTarget2(
            JDBCUtils.isNull(resultSet, offset + index) ? null : resultSet.getLong(offset + index++) // id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(ResultSet resultSet, ToOneTarget2 entity, int offset) throws SQLException {
		int index = 1;
        entity.setId(JDBCUtils.isNull(resultSet, offset + index) ? null : resultSet.getLong(offset + index++));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ToOneTarget2 entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ToOneTarget2 entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
